export const productObjs = [
  {
    heading: "Workstations",
    items: [
      "WORKING STATIONS / ASSEMBLY STATIONS",
      "IRON STEEL TABLES",
      "ALIMINIUM PROFILE",
      "STAINLESS STEEL TABLES",
      "ROLLER CONVEYORS",
      "ESD BELT CONVEYOR",
      "SCREWING",
      "STATIONS",
      "SOLDERING STATIONS",
    ],
    img: "/workstations.png",
  },
  {
    heading: "Assembly Jigs, Fixtures and Testing Equipment",
    items: [
      "SOLDERING FIXTURESTHROUGH HOLE ASSEMBLY FIXTURES WITH POKA YOKE DEPANELING JIGS",
      "IM TESTER",
      "FUNCTIONAL TESTER",
      "TESTING JIGS",
      "WAVE SOLDERING PALLETS",
      "SELECTIVE SOLDERING PALLETS",
      "AIR LEAK TESTER",
      "AGING TESTEREPOXY DISPENSING",
      "CURING FIXTURE",
    ],
    img: "/assem_jigs_t_equip.png",
  },
  {
    heading: "Process Automation / Special Purpose Machine",
    items: [
      "SPMS, ASSEMBLY CONVEYORS",
      "LINKING CONVEYORS",
      "X-Y TABLES",
      "ROBOTS",
      "ROBOTIC ARMS",
      "KOBOT",
      "DE-PANELLING AND ROUTING PROCESS",
      "SCREWING PROCESS",
      "GLUING PROCESS",
      "HEAT SHRINK PASTE APPLYING",
      "SOLDERING AUTOMATION WITH ROBOT ",
      "POKA-YOKE AT TESTING WITH MARKING (INKJET PRINTER, LASER PRINTER, ENGRAVER",
    ],
    img: "/proc_auto.png",
  },
  {
    heading: "Material Storage and Handling Equipment",
    items: [
      "REEL TROLLEY",
      "FEEDER TROLLEY",
      "MATERIAL HANDLING TROLLEY",
      "SIDE TROLLEY",
      "SUITE",
      "BIN STORAGE RACKS",
      "TROLLEYS",
      "STEEL RACKS FOR JIGS & FIXTURES STORAGE",
      "STENCIL STORAGE RACKS",
      "COMPONENT REEL STORAGE TROLLEYS",
      "MAGAZINE STORAGE TROLLEY",
    ],
    img: "/handling_equip.png",
  },
];
